export const ADD_SONGS = 'ADD_SONGS';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const ITEMS_ERROR = 'ITEMS_ERROR';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';